### ISSUE TITLE
MultiWOZ 2.1?

### ISSUE THREAD

**Issue by aatkinson** [ConvLab/ConvLab#67]
I was wondering if there were any plans to add support and NLU models for the MultiWOZ 2.1 corpus released this summer? https://www.repository.cam.ac.uk/handle/1810/294507

It looks like this project is build around MultiWOZ 2.0

**Comment by jincli** [comment]
@aatkinson  Thanks for raising this question. 

In terms of the final evaluation, the influence of changing the corpus to MultiWOZ 2.1 is limited, since we only use automatic e2e evaluation (with NLU model) to filter out very bad submissions and rank the submissions based on human evaluation.  However, for participants, you are free to use MultiWOZ 2.1 to build your own NLU models.
 
MultiWOZ 2.1 was published in the middle of the challenge. We have kept the setting of using MultiWOZ 2.0 to keep things consistent as of now. In the meanwhile, we are working on adding support for MultiWOZ 2.1 corpus in ConvLab, but due to limited bandwidth, we can not guarantee it can be released promptly for the challenge. 

Hope this helps

**Comment by aatkinson** [comment]
thanks @jincli , was just curious if 2.1 was going to be used in the challenge. we'll continue to use MultiWOZ 2.0 as supported by this project
