### ISSUE TITLE
about automatic evaluation

### ISSUE THREAD

**Issue by DH95** [ConvLab/ConvLab#79]
hello, I am the participant of DSTC8 track1 task1, and today results of automatic evaluation was released. 
I have some question about the evaluator used in the automatic evaluation.
While we were evaluating our model, we found a strange case.
<img width="507" alt="스크린샷 2019-10-15 오후 3 32 23" src="https://user-images.githubusercontent.com/30369519/66826350-3e846c00-ef87-11e9-96dc-473f17ab0268.png">
as shown in the image, milu NLU always detect 'parking' and 'internet' slot value as 'none' value even if we give correct responses.
But, in evaluator, 
![image](https://user-images.githubusercontent.com/30369519/66825937-40016480-ef86-11e9-9136-bcc0782fb7f1.png)
_check_value function return False when value is 'none'.
The problem is that there are many cases like this. So if we allow 'none' value to pass the _check_value function, our model's success rate increases almost 10% . 
Could you please check this issue?

**Comment by jincli** [comment]
@DH95  Thanks for raising this issue. If we allow 'none', that would only increase the success rate for all participants, without solving the real problem. Since this issue is due to the imperfection of milu, we will looking into improving milu model. 

As for the evaluation for the challenge, we understand that automatic evaluation is not perfect, so we
 will send as many systems as possible for human evaluation. The final ranking will only reply on human evaluation result. 

Hope this helps.

**Comment by DH95** [comment]
Thank you for your answer!
