### ISSUE TITLE
About the evaluation

### ISSUE THREAD

**Issue by DarrenZhu1103** [ConvLab/ConvLab#80]
We found some bugs in `convlab/evaluator/multiwoz.py`. So is the code used in automatic evaluation the same as `convlab/evaluator/multiwoz.py`? If the code is different, did you fix the bugs such as the bug in issue 79.

**Comment by truthless11** [comment]
@DarrenZhu1103 Could you tell us the bugs you found?

**Comment by DarrenZhu1103** [comment]
We found that some of the mistakes are due to the "?" in the database. Although you change the line 214 in `convlab/evaluator/multiwoz.py`, the nlu module of user could not recognize `?` in the sentence. And did you check if any submissions replaced the `?` with other strings before system output `sys_output` in the automatic evaluation? In human evaluation, will `?` impact the users' experience?

**Comment by truthless11** [comment]
Automatic evaluation just provides some reference for the system performance since 1) we cannot get a perfect NLU model to extract the slot values system expresses and 2) it is difficult to judge if the informed values are correct or are the ones that the user actually wants due to abbreviation, synonym, typos, etc. 

The `_check_value` function in `convlab/evaluator/multiwoz.py` works well in most cases, though not in all cases. We would not check all the submissions about how they replace "?" with other strings because it is a laborious process.

In human evaluation, the system will be interacted with real users using natural language, and the final ranking will depend on the results of human evaluation.
