### ISSUE TITLE
About human evaluation and Amazon Mechanical Turk

### ISSUE THREAD

**Issue by jeonggwanlee** [ConvLab/ConvLab#89]
Dear ConvLab Organizers, 

Thank you for organizing ConvLab! 
I participated in Track 1 Task1 End-to-End Multi-Domain Dialog Challenge in DSTC8.
I want to redo the “human evaluation process” in ConvLab and get human evaluation score using Amazon Mechanical Turk.
I also found the “convlab.human_eval” in convlab official github page.

But, I’m not sure the codes in the “convlab.human_eval” itself can be used in AMT system (I guessed it's hard to use directly for my case), and I don’t have any experience of AMT system.

If I can, I hope to upload the human evaluation code in AMT and evaluate my model.

I have 5 questions.
1. Can I use human_eval codes in convlab github page?

2. Are the codes in the “convlab.human_eval” itself (published in convlab) can be used in AMT system?

3. Can you give a brief introduction to use ConvLab Human Evaluation code? If it is complicated, a tiny suggestion also helps me a lot.

4. By the way, Can you explain me how each crowd-workers work?  (#81  might be related). 
I hope to know the exact way to evaluate.
For example, Each worker interacts one model and marks such that

a. task success, fail 
(Option 1 :He/she didn’t check whether the booked information is appropriate into the goal’s informable slot and didn’t check requestable slots. He/she just only check the flow of conversation is natural.
Option 2: He/she “strictly” check the booked information is fitted on the goal’s informable slot and check requestable slots.
Option 3: All the criteria is up to each crowd-worker.)

b. language understanding score on the 5 point scale, 
c. response appropriateness score on the 5 point scale.
(This is what I guessed.)

5. Minor question is how to encourage the AMT crowd workers work faithfully to prevent from unfaithful participation? 
For example, The base reward is small but, when they accomplish something, the success reward will be granted.

Thank you for reading.

Sincerely yours,
Jeong-gwan Lee

**Comment by pengbaolin** [comment]
Hi Jeong-gwan,

Thanks for your question. convlab.human_eval is the code we used to conduct human evaluation. 

1. Yes, you can use human_eval codes in ConvLab GitHub page.  
2. Yes. 
3. Our code has a dependency on ParlAI to conduct human evaluation. Please clone this repo at https://github.com/facebookresearch/ParlAI and point the PYTHONPATH env to that repo. You need an AWS account and a Heroku account to host the backend server. Firstly start the server by running bot_server.py and then running run.py to deploy AMT service on Heroku.
4. Your guess is correct. All the criteria are up to each crowd-worker. But you can set qualifications to ensure the worker can at least finish the task correctly.
5. The reward is actually delayed. We can bonus the workers if they finish the task seriously otherwise the reward is voided.

Best
Baolin

**Comment by jeonggwanlee** [comment]
Thank you for your kind reply!
It's helpful for me. I'll try it!!
